using Gma.CodeCloud.Controls.TextAnalyses.Blacklist;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Detextive.ViewModel
{
    public class BannedWords : CommonBlacklist
    {
        private static readonly string[] s_TopCommonWords =
            new[]
            { "acá" ,
              "ahí" ,
                 
                "al" ,
                "algo" ,
                "algún" ,
                "alguna",
                "alguno",
                "algunas",
                "algunos",
                "allá" ,
                "allí" ,
                "ambos" ,
                "ante" ,
                "antes" ,
                "aquel" ,
                "aquellas" ,
                "aquello" ,
                "aquellas" ,
                "aquellos" ,
               
                "así" ,
                "atrás" ,
                "aun" ,
                "aunque" ,
                 
                "bastante" ,
                
                "cabe" ,
                "cada" ,
                "casi" ,
                 
                "cierta" ,
                "ciertos" ,
                "ciertas" ,
                "como" ,
                "con" ,
               
                "conseguimos" ,
                "conseguir" ,
                "consigo" ,
                "consigue" ,
                "consiguen" ,
                "consigues" ,
                "contigo" ,
                 
                "cual" ,
                "cuales" ,
                "cualquier" ,
                "cualquiera" ,
                "cualquieras" ,
                "cualesquiera" ,
                "cuan" ,
                "cuando" ,
                "cuanto" ,
                "cuanta" ,
                "cuantos" ,
                "cuantas" ,
                "de" ,
                "dejar" ,
                "del" ,
                "demás" ,
                "demasiadas" ,
                "demasiada" ,
                "demasiado" ,
                "demasiados" ,
                
                "desde" ,
                "donde" ,
                "dos" ,
                "el" ,
                "él" ,
                "ella" ,
                "ellas" ,
                "ellos" ,
             
                "en" ,
               
                "entonces" ,
                "entre" ,
                "era",
                "eras" ,
                "eramos" ,
                "eran" ,
                "eres" ,
                "es" ,
                "esos" ,
                "esa" ,
                "eso" ,
                "ese" ,
                "esas" ,
                "estas" ,
                "esta" ,
                "estaba" ,
               
                "estáis" ,
                "estamos" ,
                "están" ,
                "estar" ,
                "este" ,
                "esto" ,
                "estos" ,
                "estés" ,
                "estoy" ,
                "etc" ,
                "fin" ,
                "fue" ,
                "fueron" ,
                "fui" ,
                "fuimos" ,
                "gueno" ,
                "ha" ,
                "haces" ,
                "hace" ,
                "hacéis" ,
                "hacemos" ,
                "hacen" ,
                "hacer" ,
                "hacia" ,
                "hago" ,
                "hasta" ,
                "incluso" ,
                "intentas" ,
                "intenta" ,
                "intentáis" ,
                "intentamos" ,
                "intentan" ,
                "intentar" ,
                "intento" ,
                "ir" ,
               
                "la" ,
                "lo" ,
                "las" ,
                "los" ,
                "largo" ,
                "más" ,
                "mas" ,
                "me" ,
                "menos" ,
                "mi" ,
                "mis" ,
                "mientras" ,
                "mío" ,
                "mía" ,
                "mías" ,
                "míos" ,
                "misma" ,
                "mismo" ,
                "mismos" ,
                "mismas" ,
                "modo" ,
                "mucha" ,
                "muchas" ,
                "muchos" ,
                "muchísima" ,
                "muchísimo" ,
                "muchísimas" ,
                "muchísimos" ,
                "mucho" ,
                "muchos" ,
                "muy" ,
                "nada" ,
                "ni" ,
                "ningún" ,
                "ninguna" ,
                "ninguno" ,
                "no" ,
                "nos" ,
                
                "nunca" ,
                "os" ,
                 
                "para" ,
               
                "pero" ,
                "poca" ,
                "poco" ,
                "pocas" ,
                "pocos" ,
                "podéis" ,
                "podemos" ,
                "poder" ,
                "podría" ,
                "podrías" ,
                "podríais" ,
                "podríamos" ,
                "podrían" ,
                "por" ,
                "por qué" ,
                "porque" ,
               
                "pueden" ,
                "puedes" ,
                "puede" ,
                "puedo" ,
                "pues" ,
                "que" ,
                "qué" ,
                "querer" ,
                "quienes" ,
                "quien" ,
                "quién" ,
                "quienesquiera" ,
                "quienquiera" ,
                "quizás" ,
                "quizá" ,
                "sabe" ,
                "sabes" ,
                "saben" ,
                "sabéis" ,
                "sabemos" ,
                "saber" ,
                "se" ,
                "según" ,
                "ser" ,
                "si" ,
                "sí" ,
 
                "siendo" ,
                "sin" ,
                "sino" ,
                "so" ,
                "sobre" ,
                "sois" ,
                "solamente" ,
                "solo" ,
                "sólo" ,
                "somos" ,
                "soy" ,
                "sr" ,
                "sra" ,
                "sres" ,
                "sta" ,
                "su" ,
                "sus" ,
                "suya" ,
                "suyo" ,
                "suyas" ,
                "suyos" ,
                "tal" ,
                "tales" ,
                "también" ,
                "tampoco" ,
                "tan" ,
                "tanta" ,
                "tanto" ,
                "tantas" ,
                "tantos" ,
                "te" ,
                "tenéis" ,
                "tenemos" ,
                "tener" ,
                "tengo" ,
                "ti" ,
              
                "tiene" ,
                "tienen" ,
                "toda" ,
                "todo" ,
                "todas" ,
                "todos" ,
                "tomar" ,
              
                "tras" ,
                "tú" ,
                "tu" ,
                "tus" ,
                "tuya " ,
                "tuyo" ,
                "tuyas" ,
                "tuyos" ,
                
                "un " ,
                "una" ,
                "uno" ,
                "unas" ,
                "unos" ,
                "usa" ,
                "usas" ,
                "usáis" ,
                "usamos" ,
                "usan" ,
                "usar" ,
                "uso" ,
                "ustedes" ,
                "usted" ,
                "va" ,
                "van" ,
                "vais" ,
              
                "vamos" ,
                "varias" ,
                "varios" ,
                "vaya" ,
                 
                "vosotras" ,
                "vosotros" ,
                "voy" ,
                "vuestra" ,
                "vuestro" ,
                "vuestras" ,
                "vuestras" ,
                "y" ,
                "ya" ,
                "yo",
                "algún",
                "alguna",
                "algunas",
                "alguno",
                "algunos",
                 
                
                "ante",
                "antes",
                "aquel",
                "aquellas",
                "aquellos",
               
               
                "bastante",
                "bien",
                "cada",
                "cierta",
                "ciertas",
                 
                "ciertos",
                "como",
                "con",
              
                "cual",
                "cuando",
                
                "desde",
                "donde",
                "dos",
                "el",
                "ellas",
                "ellos",
                "empleais",
                
                "en",
                "encima",
                "entonces",
                "entre",
                "era",
                "eramos",
                "eran",
                "eras",
                "eres",
                "es",
                "esta",
                "estaba",
                "estado",
                "estais",
                "estamos",
                "estan",
                "estoy",
                 
                "fue",
                "fueron",
                "fui",
                "fuimos",
                "gueno",
                "ha",
                "hace",
                "haceis",
                "hacemos",
                "hacen",
                "hacer",
                "haces",
                "hago",
                "incluso",
                "intenta",
                "intentais",
                "intentamos",
                "intentan",
                "intentar",
                "intentas",
                "intento",
                "ir",
                "la",
                "largo",
                "las",
                "lo",
                "los",
                "mientras",
                "mio",
                "modo",
                "muchos",
                "muy",
                "nos",
                 
                "para",
                "pero",
                "podeis",
                "podemos",
                "poder",
                "podria",
                "podriais",
                "podriamos",
                "podrian",
                "podrias",
                "por",
                "por qué",
                "porque",
                "primero",
                "puede",
                "pueden",
                "puedo",
                "quien",
                "sabe",
                "sabeis",
                "sabemos",
                "saben",
                "saber",
                "sabes",
                "ser",
                "si",
                "siendo",
                "sin",
                "sobre",
                "sois",
                "solamente",
                "solo",
                "somos",
                "soy",
                "su",
                "sus",
                "también",
                "teneis",
                "tenemos",
                "tener",
                "tengo",
               
                "tiene",
                "tienen",
                "todo",
                "trabaja",
                "trabajais",
                "trabajamos",
                "trabajan",
                "trabajar",
                "trabajas",
                 
                "tras",
                "tuyo",
                "ultimo",
                "un",
                "una",
                "unas",
                "uno",
                "unos",
                "usa",
                "usais",
                "usamos",
                "usan",
                "usar",
                "usas",
                "uso",
                "va",
                "vais",
                "valor",
                "vamos",
                "van",
                "vaya",
                
                "vosotras",
                "vosotros",
                "voy",
                "yo",
                "él",
                "ésta",
                "éstas",
                "éste",
                "éstos",
                "última",
                "últimas",
                "último",
                "últimos",
                "a",
                "añadió",
                "aún",
                "actualmente",
                "adelante",
                "además",
                "afirmó",
                "agregó",
                "ahí",
                "ahora",
                "al",
                "algo",
                "alrededor",
                "anterior",
                "apenas",
                "aproximadamente",
                "aquí",
                "así",
                "aseguró",
                "aunque",
                
                "buen",
                
                "cómo",
                "casi",
                
                "cinco",
                "comentó",
                "conocer",
                "consideró",
                "considera",
                "contra",
                "cosas",
                "creo",
                "cuales",
                "cualquier",
                "cuanto",
                "cuatro",
                "cuenta",
                "da",
                "dado",
                "dan",
                "dar",
                "de",
                "debe",
                "deben",
                "debido",
                "decir",
                "dejó",
                "del",
                "demás",
                "después",
                "dice",
                "dicen",
                "dicho",
                "dieron",
                
                "dijeron",
                "dijo",
                "dio",
                "durante",
                "e",
                "ejemplo",
                "ella",
                "ello",
                
                "encuentra",
                "esa",
                "esas",
                "ese",
                "eso",
                "esos",
                "está",
                "están",
                "estaban",
                "estar",
                "estará",
                "estas",
                "este",
                "esto",
                "estos",
                "estuvo",
                "ex",
               
                "explicó",
                "expresó",
                
                
                "había",
                "habían",
                "haber",
                "habrá",
                "hacerlo",
                "hacia",
                "haciendo",
                "han",
                "hasta",
                "hay",
                "haya",
                "he",
                "hecho",
                "hemos",
                "hicieron",
                "hizo",
                "hoy",
                "hubo",
                "igual",
                "indicó",
                "informó",
                "junto",
                "lado",
                "le",
                "les",
                "llegó",
                "lleva",
                "llevar",
                "luego",
               
                "más",
                "manera",
                "manifestó",
                "mayor",
                "me",
                "mediante",
                "mejor",
                "mencionó",
                "menos",
                "mi",
                "misma",
                "mismas",
                "mismo",
                "mismos",
               
                "mucha",
                "muchas",
                "mucho",
                "nada",
                "nadie",
                "ni",
                "ningún",
                "ninguna",
                "ningunas",
                "ninguno",
                "ningunos",
                "no",
                "nosotras",
                "nuestra",
                "nuestras",
                "nuestro",
                "nuestros",
                "nueva",
                "nuevas",
                "nuevo",
                "nuevos",
                "nunca",
                "o",
                "ocho",
                "otra",
                "otras",
                "otros",
                "parece",
                "parte",
                "partir",
                "pasada",
               
                "pesar",
                "poca",
                "pocas",
                "poco",
                "pocos",
                "podrá",
                "podrán",
                "podría",
                "podrían",
                "poner",
                "posible",
                "próximo",
                "próximos",
                "primer",
                "primera",
                "primeros",
                "principalmente",
               
                "pudo",
                "pueda",
                "pues",
                "qué",
                "que",
                "quedó",
                "queremos",
                "quién",
                "quienes",
                "quiere",
                "realizó",
                "realizado",
                "realizar",
                "respecto",
                "sí",
                "sólo",
                "se",
                "señaló",
                "sea",
                "sean",
                "según",
                "segunda",
                "segundo",
                "seis",
                "será",
                "serán",
                "sería",
                "sido",
                
                "siete",
                "sigue",
                "siguiente",
                "sino",
                "sola",
                "solas",
                "solos",
                "son",
                "tal",
                "tampoco",
                "tan",
                "tanto",
                "tenía",
                "tendrá",
                "tendrán",
                "tenga",
                "tenido",
                "tercera",
                "toda",
                "todas",
                "todavía",
                "todos",
                "total",
               
                "través",
                "tres",
                "tuvo",
                "usted",
                "varias",
                "varios",
                "veces",
                "ver",
                "vez",
                "y",
                "ya"};

        public BannedWords() : base(s_TopCommonWords)
        {
        }
    }
}
